/**
 * WEBPACK_CONIFG_HOST的值，在webpack.config.js中更改
 * 开发环境时 = "http://amptest.wisedu.com/xsfwfw/"
 * 发布环境时 = location.origin + location.pathname.substring(0, location.pathname.indexOf("/", 1)) + "/"
 */
let jbxx='sys/jzgxxglxt/modelpage/xxgl/';
let kzxx='sys/jzgxxglxt/modelpage/kzxxgl/';
export default {
    getWechatSign: 'sys/jzgxxglxt/modelpage/xxgl/',
    //获取登陆人信息
    dqdlrxxcx:jbxx+'dqdlrxxcx.do',
    //基本信息
    jbxxQuery:jbxx+'T_JZG_JBXX_QUERY.do',
    jbxxSave:jbxx+'T_JZG_JBXX_SAVE.do',
      //语言能力
    yynlQuery:kzxx+'T_JZG_YYNL_QUERY.do',
    yynlDelete:kzxx+'T_JZG_YYNL_DELETE.do',
    yynlSave:kzxx+'T_JZG_YYNL_SAVE.do',
      //工作经历
    gzjlQuery:kzxx+'T_JZG_GZJL_QUERY.do',
    gzjlDelete:kzxx+'T_JZG_GZJL_DELETE.do',
    gzjlSave:kzxx+'T_JZG_GZJL_SAVE.do',
     //学历学位信息
    xlxwQuery:kzxx+'T_JZG_XLXW_QUERY.do',
    xlxwDelete:kzxx+'T_JZG_XLXW_DELETE.do',
    xlxwSave:kzxx+'T_JZG_XLXW_SAVE.do',
     //工人等级
    grjsdjQuery:kzxx+'T_JZG_GRJSDJ_QUERY.do',
    grjsdjDelete:kzxx+'T_JZG_GRJSDJ_DELETE.do',
    grjsdjSave:kzxx+'T_JZG_GRJSDJ_SAVE.do',
     //考核信息
    khQuery:kzxx+'T_JZG_KH_QUERY.do',
    khDelete:kzxx+'T_JZG_KH_DELETE.do',
    khSave:kzxx+'T_JZG_KH_SAVE.do',
     //政治面貌
    zzmmQuery:kzxx+'T_JZG_ZZMM_QUERY.do',
    zzmmDelete:kzxx+'T_JZG_ZZMM_DELETE.do',
    zzmmSave:kzxx+'T_JZG_ZZMM_SAVE.do',
     //行政与党派任职（聘任）经历
    xzydprzjlQuery:kzxx+'T_JZG_XZYDPRZJL_QUERY.do',
    xzydprzjlDelete:kzxx+'T_JZG_XZYDPRZJL_DELETE.do',
    xzydprzjlSave:kzxx+'T_JZG_XZYDPRZJL_SAVE.do',
     //技术工人聘任经历
    jsgrpyjlQuery:kzxx+'T_JZG_JSGRPYJL_QUERY.do',
    jsgrpyjlDelete:kzxx+'T_JZG_JSGRPYJL_DELETE.do',
    jsgrpyjlSave:kzxx+'T_JZG_JSGRPYJL_SAVE.do',
     //兼任其他单位职务经历
    jrqtdwzwjlQuery:kzxx+'T_JZG_JRQTDWZWJL_QUERY.do',
    jrqtdwzwjlDelete:kzxx+'T_JZG_JRQTDWZWJL_DELETE.do',
    jrqtdwzwjlSave:kzxx+'T_JZG_JRQTDWZWJL_SAVE.do',
       //专业技术资格信息
    zyjszgxxQuery:kzxx+'T_JZG_ZYJSZGXX_QUERY.do',
    zyjszgxxDelete:kzxx+'T_JZG_ZYJSZGXX_DELETE.do',
    zyjszgxxSave:kzxx+'T_JZG_ZYJSZGXX_SAVE.do',
       //职业资格信息
    zyzgxxQuery:kzxx+'T_JZG_ZYZGXX_QUERY.do',
    zyzgxxDelete:kzxx+'T_JZG_ZYZGXX_DELETE.do',
    zyzgxxSave:kzxx+'T_JZG_ZYZGXX_SAVE.do',
       //博士后研究人员信息
    bshyjryxxQuery:kzxx+'T_JZG_BSHYJRYXX_QUERY.do',
    bshyjryxxDelete:kzxx+'T_JZG_BSHYJRYXX_DELETE.do',
    bshyjryxxSave:kzxx+'T_JZG_BSHYJRYXX_SAVE.do',
       //教育培训经历
    jypxjlQuery:kzxx+'T_JZG_JYPXJL_QUERY.do',
    jypxjlDelete:kzxx+'T_JZG_JYPXJL_DELETE.do',
    jypxjlSave:kzxx+'T_JZG_JYPXJL_SAVE.do',
       //经费形式变动记录
    sydwjfbdjlQuery:kzxx+'T_JZG_SYDWJFBDJL_QUERY.do',
    sydwjfbdjlDelete:kzxx+'T_JZG_SYDWJFBDJL_DELETE.do',
    sydwjfbdjlSave:kzxx+'T_JZG_SYDWJFBDJL_SAVE.do',
       //来华工作信息
    lhgzxxQuery:kzxx+'T_JZG_LHGZXX_QUERY.do',
    lhgzxxDelete:kzxx+'T_JZG_LHGZXX_DELETE.do',
    lhgzxxSave:kzxx+'T_JZG_LHGZXX_SAVE.do',
       //人事档案调动记录
    rsdaddjlQuery:kzxx+'T_JZG_RSDADDJL_QUERY.do',
    rsdaddjlDelete:kzxx+'T_JZG_RSDADDJL_DELETE.do',
    rsdaddjlSave:kzxx+'T_JZG_RSDADDJL_SAVE.do',
       //奖励信息
    jlxxQuery:kzxx+'T_JZG_JLXX_QUERY.do',
    jlxxDelete:kzxx+'T_JZG_JLXX_DELETE.do',
    jlxxSave:kzxx+'T_JZG_JLXX_SAVE.do',
        //惩处信息
    ccxxQuery:kzxx+'T_JZG_CCXX_QUERY.do',
    ccxxDelete:kzxx+'T_JZG_CCXX_DELETE.do',
    ccxxSave:kzxx+'T_JZG_CCXX_SAVE.do',
        //政治运动表现
    zzydbxQuery:kzxx+'T_JZG_ZZYDBX_QUERY.do',
    zzydbxDelete:kzxx+'T_JZG_ZZYDBX_DELETE.do',
    zzydbxSave:kzxx+'T_JZG_ZZYDBX_SAVE.do',
        //休假信息
    xjxxQuery:kzxx+'T_JZG_XJXX_QUERY.do',
    xjxxDelete:kzxx+'T_JZG_XJXX_DELETE.do',
    xjxxSave:kzxx+'T_JZG_XJXX_SAVE.do',
        //工伤信息
    gsxxQuery:kzxx+'T_JZG_GSXX_QUERY.do',
    gsxxDelete:kzxx+'T_JZG_GSXX_DELETE.do',
    gsxxSave:kzxx+'T_JZG_GSXX_SAVE.do',
        //考勤信息
    kqxxQuery:kzxx+'T_JZG_KQXX_QUERY.do',
    kqxxDelete:kzxx+'T_JZG_KQXX_DELETE.do',
    kqxxSave:kzxx+'T_JZG_KQXX_SAVE.do',
        //专业技术职务聘用经历
    zjzwprjlQuery:kzxx+'T_JZG_ZJZWPRJL_QUERY.do',
    zjzwprjlDelete:kzxx+'T_JZG_ZJZWPRJL_DELETE.do',
    zjzwprjlSave:kzxx+'T_JZG_ZJZWPRJL_SAVE.do'
}